# Generated by Django 4.2.7 on 2026-03-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listview",
            name="view_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
